version: '3.3'

services:
  suporte_postgres_service:
    image: postgis/postgis:16-3.4
    container_name: suporte_postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_DOCKER}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - suporte_postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      GUNICORN_CMD_ARGS: "--log-level critical"
    ports:
      - "5060:80"
    depends_on:
      - suporte_postgres_service
    networks:
      - suporte_postgres_network
  suporte_app_service:
    build: .
    container_name: suporte_app_container
    ports: 
      - "8030:8030"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      FOLDER_CAR: ${FOLDER_CAR}
    volumes:
      - .:/usr/src/suporte
      - ${FOLDER_CAR}:${FOLDER_CAR}
    depends_on:
      - suporte_postgres_service
    restart: always
    networks:
      - suporte_postgres_network
    tty: true

networks:
  suporte_postgres_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
